env:
  browser: true
  es2021: true
extends:
  - airbnb
  - eslint:recommended
  - plugin:react/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: 
  react/function-component-definition: [2, { "namedComponents": "arrow-function" }]
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }]
  no-console: 0
  import/extensions: 0
  import/no-unresolved: 0

